CScorner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_items, show_items, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-items/', create_items, name='create_items'),
    path('items/<str:id>/', show_items, name='show_items'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:items_id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:items_id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class Items(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    CATEGORY_CHOICES = [
        ('sepatu', 'Sepatu Bola'),
        ('jersey', 'Baju Jersey'),
        ('training', 'Celana Training'),
        ('jaket', 'Jaket'),
        ('bola', 'Bola'),
        ('tas', 'Tas Bola'),
        ('poster', 'Poster'),
        ('figur', 'Figur Pemain'),
        ('aksesoris', 'Aksesoris'),
    ]

    SIZE_CHOICES = [
        ('s', 'S'),
        ('m', 'M'),
        ('l', 'L'),
        ('xl', 'XL'),
        ('xxl', 'XXL'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.PositiveIntegerField()
    description = models.TextField()
    thumbnail = models.URLField(blank=True, null=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='update')
    is_featured = models.BooleanField(default=False)
    size = models.CharField(max_length=20, choices=SIZE_CHOICES, default='update')
    items_views = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.name
        
    def increment_views(self):
        self.items_views += 1
        self.save()

main/forms.py
from django.forms import ModelForm
from main.models import Items

class ItemsForm(ModelForm):
    class Meta:
        model = Items
        fields = ["name", "price", "description", "thumbnail", "category", "is_featured"]

class ItemsSizeForm(ModelForm):
    class Meta:
        model = Items
        fields = ["name", "price", "description", "thumbnail", "category", "is_featured", "size"]

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from main.forms import ItemsForm, ItemsSizeForm
from main.models import Items
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    filter_type = request.GET.get("filter", "all")
    if filter_type == "all":
        items_list = Items.objects.all()
    else:
        items_list = Items.objects.filter(user=request.user)

    context = {
        'app' : 'CS Corner',
        'name': request.user.username,
        'class': 'PBP C',
        'items_list': items_list,
        'last_login': request.COOKIES.get('last_login', 'Never')
    }

    return render(request, "main.html", context)

def create_items(request):
    form_class = ItemsForm

    if request.method == "POST":
        category = request.POST.get('category')
        if category in ['jersey', 'jaket']:
            form_class = ItemsSizeForm
        form = form_class(request.POST)
        if form.is_valid():
            # form.save()
            items_entry = form.save(commit = False)
            items_entry.user = request.user
            items_entry.save()
            return redirect('main:show_main')
    else:
        form = ItemsForm()

    context = {'form': form}
    return render(request, "create_items.html", context)

@login_required(login_url='/login')
def show_items(request, id):
    items = get_object_or_404(Items, pk=id)
    items.increment_views()

    context = {
        'items': items
    }

    return render(request, "items_detail.html", context)

def show_xml(request):
    items_list = Items.objects.all()
    xml_data = serializers.serialize("xml", items_list)
    return HttpResponse(xml_data, content_type="application/xml")

def show_json(request):
    items_list = Items.objects.all()
    json_data = serializers.serialize("json", items_list)
    return HttpResponse(json_data, content_type="application/json")

def show_xml_by_id(request, items_id):
    try:
        items_item = Items.objects.filter(pk=items_id)
        xml_data = serializers.serialize("xml", items_item)
        return HttpResponse(xml_data, content_type="application/xml")
    except Items.DoesNotExist:
        return HttpResponse(status=404)

def show_json_by_id(request, items_id):
    try:
        items_item = Items.objects.get(pk=items_id)
        json_data = serializers.serialize("json", [items_item])
        return HttpResponse(json_data, content_type="application/json")
    except Items.DoesNotExist:
       return HttpResponse(status=404)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

main/templates/create_items.html
{% extends 'base.html' %} 
{% block content %}
<h1 style="color: blue;">Add Product</h1>

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Add PRODUCT" style="background-color: rgba(0, 136, 255, 0.368); color: black;"/>
      </td>
    </tr>
  </table>
</form>

{% endblock %}

main/templates/items_detail.html
{% extends 'base.html' %}
{% block content %}
<p><a href="{% url 'main:show_main' %}"><button style="background-color: rgba(0, 136, 255, 0.368); color: black;">← Back to Product List</button></a></p>

<h1>{{ items.name }}</h1>
<p>
    <b>Category:</b>{{ items.get_category_display }} {% if items.is_featured %} | 
    <b>Featured</b>{% endif %} | Views: {{ items.items_views }}
    <br>
    <b>Price:</b> Rp{{ items.price }}
    {% if items.size != 'update' %}
    <br>
    <b>Size:</b> {{ items.get_size_display }}
    {% endif %}
</p>

{% if items.thumbnail %}
<img src="{{ items.thumbnail }}" alt="Product thumbnail" width="300">
<br /><br />
{% endif %}

<p>{{ items.description }}</p>

{% if items.user %}
    <p>Author: {{ items.user.username }}</p>
{% else %}
    <p>Author: Anonymous</p>
{% endif %}

{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="login">
  <h1>Login</h1>

  <form method="POST" action="">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td><input class="btn login_btn" type="submit" value="Login" style="background-color: rgba(0, 136, 255, 0.368); color: black;"/></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %} Don't have an account yet?
  <a href="{% url 'main:register' %}">Register Now</a>
</div>

{% endblock content %}

main/templates/main.html
<h1 style="color: blue">Welcome to CS Corner</h1>

<h4>Aplikasi: </h4>
<p>{{ app }}</p>

<h4>Name: </h4>
<p>{{ name }}</p>
 
<h4>Class: </h4>
<p>{{ class }}</p> 

<a href="{% url 'main:create_items' %}">
  <button style="background-color: rgba(0, 136, 255, 0.368); color: black;">+ Add Product</button>
</a>
<a href="{% url 'main:logout' %}">
  <button style="background-color: rgba(0, 136, 255, 0.368); color: black;">Logout</button>
</a>
<h5>Sesi terakhir login: {{ last_login }}</h5>
<hr>

<a href="?filter=all">
    <button type="button" style="background-color: rgba(0, 136, 255, 0.368); color: black;">All Products</button>
</a>
<a href="?filter=my">
    <button type="button" style="background-color: rgba(0, 136, 255, 0.368); color: black;">My Products</button>
</a> 

{% if not items_list %}
<p>Belum ada informasi produk pada CS Corner.</p>
{% else %}

{% for items in items_list %}
<div>
    <h2><a href="{% url 'main:show_items' items.id %}">{{ items.name }}</a></h2>
    <p><b>{{ items.get_category_display }}</b>{% if items.is_featured %} |
        <b>Featured</b> | <b>Price:</b> Rp{{ items.price }}{% endif %} | Views: {{ items.items_views }}</p>

    {% if items.thumbnail %}
    <img src="{{ items.thumbnail }}" alt="thumbnail" width="150" height="100">
    <br />
    {% endif %}

    <p>{{ items.description|truncatewords:25 }}...</p>

    <p><a href="{% url 'main:show_items' items.id %}"><button style="background-color: rgba(0, 136, 255, 0.368); color: black;">Read More</button></a></p>
</div>

<hr>
{% endfor %}

{% endif %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}

<div>
  <h1>Register</h1>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td><input type="submit" name="submit" value="Daftar" style="background-color: rgba(0, 136, 255, 0.368); color: black;"/></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
</head>

<body>
    {% block content %} {% endblock content %}
</body>
</html>